### PR TITLE
Unsupervised Learning Translation

### PR DESCRIPTION
**Pull request by erfannoury**

### CODE REVIEW

**Review by mhd-karimi — COMMENTED** [review]
Well, you've got some plural translation wrong:
8th statement `comments` is plural: `توضیحات`
10th `parameter` is single: `پارامتر`

11th: typo  `محاسبه`

18th should change to:
تابع اعوجاج - برای تشخیص اینکه الگوریتم به هم‌گرایی رسیده است، `به` تابع اعوجاج که به صورت زیر تعریف می‌شود رجوع می‌کنیم

22: there is an extra `ّ`
26: typo `خوشه`

**Comment by erfannoury** [comment]
@m-karimi I've fixed the typos and finished the translations. Can you take one final look? Thanks :)

**Comment by mhd-karimi** [comment]
37: an extra space would be more pleasant after `:` mark

39: بردار`های` ویژه‌ی اصلی متعامد

37, 38, 39, 40: in step 1, you've used plural first person active verb form while translating the others with a passive verb form. I think using the same verb form for all steps results in better understanding. 

45: extra `یک`
فرض می‌کنیم که داده‌ی ایکس توسط `یک` بردار

49: I find it in a pretty different style from other translations, maybe using something like this: 
`لگاریتم درست‌نمایی با توجه به داده‌های آموزش .... و نمایش تابع سیگموئید با نماد جی به صورت زیر نوشته می‌شود`

50: no translation for `stochastic`. 
`gradient ascent`: `گرادیان افزایشی`
it should be like the translation we had for gradient descent before.
‍‍`for each training example`: `برای هر نمونه از داده‌های آموزش`

**Comment by erfannoury** [comment]
@m-karimi Thank you very much for the great suggestions. I edited the translations according to them.

**Comment by mhd-karimi** [comment]
Good job, just one more thing before merge:
The correct translation of Sigmoid is `سیگموئید`.

In the last sentence, I find using `برای هر نمونه از داده‌های آموزش` is easier to grasp in comparison to  `برای هر نمونه‌ی داده‌های آموزش`.

**Pull request merged**
