### PR TITLE
Probability Refresher Translation

### PR DESCRIPTION
**Pull request by erfannoury**
This PR will track translations of the Probability Refresher document.

### CODE REVIEW

**Review by mhd-karimi — COMMENTED** [review]
I've got three suggestion edit based on Wikipedia articles and their usage:
`event`: `پیشامد`
you could use `رخداد` or ‍‍`رویداد` --> https://fa.wikipedia.org/wiki/%D9%BE%DB%8C%D8%B4%D8%A7%D9%85%D8%AF
`Probability density function` : `تابع چگالی احتمال` --> https://fa.wikipedia.org/wiki/%D8%AA%D8%A7%D8%A8%D8%B9_%DA%86%DA%AF%D8%A7%D9%84%DB%8C_%D8%A7%D8%AD%D8%AA%D9%85%D8%A7%D9%84
`Moments` : `گشتاور` --> https://fa.wikipedia.org/wiki/%DA%AF%D8%B4%D8%AA%D8%A7%D9%88%D8%B1_(%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C)

**Comment by erfannoury** [comment]
I have پیشامد for outcomes in the translation, but I think رخداد is a good translation for event.
I will change the rest as you have suggested.

**Comment by erfannoury** [comment]
@m-karimi I applied your suggested changes.

**Comment by mhd-karimi** [comment]
Well done, I have had an additional suggestion that wasn't sure about it.
I think the word `پیش قدر` ‍‍is not too common.
using `خطا` or something alike would be more understandable. 
(e. g. the 50th sentence will be:
`یک تخمین گر بدون خطاست اگر داشته باشیم E[^θ]=θ`)

**Comment by erfannoury** [comment]
I know that پیش‌قدر isn't commonly used, but I think this is an opportunity to introduce the word. Since I don't think that خطا is actually a correct translation for bias.

**Comment by mhd-karimi** [comment]
Okay, so you have to change the 50th sentence anyway:
`یک تخمین‌گر بدون پیش‌قدر است `
Is there any other part you think I have to double check?
Other than that you are good to go.

**Comment by erfannoury** [comment]
That's correct. Thank you for pointing that out. How do you want me to add your name to the contributer's list? (Github username, fullname, [Mohammad Karimi](https://github.com/m-karimi))

**Comment by mhd-karimi** [comment]
Mentioning Github username would be nice but do it as you do to your name, consistency would be more pleasant.

**Pull request merged**
